# @author SQ Group 31, Rolf-Jaden Sibal

name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy w/ Maven
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK and Maven Settings
      uses: actions/setup-java@v3
      with:
        java-version: '21' 
        distribution: 'temurin'
        server-id: github # This should match the <id> in your <distributionManagement> section in pom.xml
        settings-path: ${{ github.workspace }} # Specifies where to generate the settings.xml

    - name: Build with Maven
      run: |
        mvn -B clean install --file pom.xml
        mvn -B deploy -s ${{ github.workspace }}/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}


# Note: Secrets.GITHUB_TOKEN is automatically created by GitHub Actions and does not need to be manually created.
