name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy w/ Maven
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: |
        mvn -B clean install --file pom.xml
        mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Note: Secrets.GITHUB_TOKEN is automatically created by GitHub Actions and does not need to be manually created.
